### ISSUE TITLE
compatibility with devtools?

### ISSUE THREAD

**Issue by Jacknq** [Raiondesu/Tuex#4]
Hi, 
thanks for your project, it makes sense to use simple api. Did you think of maybe to make it vuex compatible in a sense that it would extend existing official vuex and mutations, actions would be backwards compatible with vue devtools vuex part also? 

thanks

**Comment by Raiondesu** [comment]
Hi there, @Jack85

As you might have noticed - Tuex is in a kiiiinda early stage of development. Version is not even close to the 1.0.

Saying this though, I did consider bringing some partial Vuex-complatibility to the list of features, including invoking setters and methods through commits and dispatches in a Vuex-compatible way. I even tried implementing all this.

And the more I tried, the more I understood the need to be patient about such things, as the Tuex-own api is not fully established yet to integrate compatibility features without eventually breaking something. And the fact that I can't work on the framework full-time adds to all this.


But it absolutely will be done as soon as most of the main features will be polished enough to make it into commercial projects (in the company I currently work for, per se).

That said, feel free to dig into the sources and make PRs. Any help is appreciated. :blush:

P.S. It is very inspiring to see people starting to get interested in the project, so thank you for reaching out to me here. :relaxed:

**Comment by Jacknq** [comment]
In this case its you inspiring others, thanks for that. 
Im not yet so deep in typescript to be able to define high level library while working like you. However there are anyway various ways f.e. making plugin or just extending existing vuex class, which might be interesting to look at for me as I progress when I get there. 
I hope sooner or later someone writes something like this, even official guys.

**Comment by Raiondesu** [comment]
@Jack85,

Anyway, Vuex-compatible api would be much more convenient in the current state of the Vue community.

I surely will implement this feature this month. One way or another.

**Comment by Raiondesu** [comment]
Vuex-compatible API is coming in v0.5.0

**Comment by Raiondesu** [comment]
Feature is implemented on the dev branch.
Release will be soon.

**Comment by Raiondesu** [comment]
Reopening this to avoid further duplicates until the release.

**Comment by emahuni** [comment]
any news on any new version of this package, this looks promising, but it looks stale. didn't wan't to open a new ticket that's why I commented here.
