### ISSUE TITLE
strange err in dev

### ISSUE THREAD

**Issue by Jacknq** [Raiondesu/Tuex#6]
Hi, when testing dev branch i get some strange error:
`node_modules\tuex\types\vue.d.ts`
(2,24): error TS2307: Cannot find module 'store'.

and when i modify path there to ../src/store
 i get 
```
\node_modules\tuex\types\vue.d.ts

(6,6): error TS2403: Subsequent variable declarations must have the same type.  Variable '$store' must be of type 'Store<any>', but here has type 'Store<any>'.

on following line in browser:
Object.defineProperty(_vue.prototype.$store, 'state', desc(stateWrapper, 'state'));

right after creating
const txstore = new Tuex.Store({
```
using npm 5.5.1, ts 2.6.2, vue 2.5.2

**Comment by Raiondesu** [comment]
Dev branch is unstable and not friendly to production environments, so I think something like this is to be expected. :c

I'm currently re-evaluating the way of types interactions, so consider this one to be "in progress".

As for the in-time fix for this - `typeof any !== typeof any` in TypeScript.
I didn't expect TS compiler to be aware of what `Object.defineProperty` does.
Maybe I really underestimated it. 😄 
For now - I recommend you to try redefining the Vue type again or pass an interface to the Tuex.Store: `... new Tuex.Store<SomeInterface>(...)`

Please, keep me updated on this one, as I couldn't really recreate it.

**Comment by Jacknq** [comment]
but the first one is that store import, that is complaining, not sure there.. 
and second one is happening in browser, compilation not successful and app wont run.

**Comment by Jacknq** [comment]
interface didnt help:
```
interface st{
  num:number, 
  increase(amount:number);
}

const txstore = new Tuex.Store<st>({
  num: 0,

  increase(amount) {
    this.num += amount;
  }
});

export default txstore;
```
node_modules\tuex\types\vue.d.ts

(6,6): error TS2403: Subsequent variable declarations must have the same type.  Variable '$store' must be of type 'Store<any>', but here has type 'Store<any>'.

seems as conflict on state class when augmenting..

**Comment by Raiondesu** [comment]
@Jack85, did you try redefining the Vue type like this:
```
import Vue from 'vue';
import { Store } from 'tuex';

declare module 'vue/types/vue' {
  interface Vue {
    $store: Store<st>;
  }
}
```
?

**Comment by Raiondesu** [comment]
BTW, @Jack85, what version of TypeScript do you have?

**Comment by Jacknq** [comment]
using npm 5.5.1, ts 2.6.2, vue 2.5.2

**Comment by Jacknq** [comment]
if do what you recommended i get following

`(6,6): error TS2403: Subsequent variable declarations must have the same type.  Variable '$store' must be of type 'Store<any>', but here has type 'Store<st>'.`

**Comment by Raiondesu** [comment]
It seems as a rightful solution to me to remove the `Vue` type redeclaration from Tuex's types.

**Comment by Jacknq** [comment]
Correct. To have it minimal as it can be, can help.
